In [ ]:
A = ('A', 'B')
B = ('C',)
C = A + B
print(C, type(C))

('A', 'B', 'C') <class 'tuple'>


In [ ]:
import numpy as np
nn = int(input())
A = np.zeros((nn,nn))
for ii in range(nn):
  for jj in range(nn):
    A[ii][jj] = ii*nn+jj+1
print(A)

5
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [ ]:
import numpy as np
nn = int(input())
A = np.zeros((nn,nn))
for ii in range(nn):
  for jj in range(nn):
    A[ii][jj] = ii*nn+jj+1
print(A)
B = A.reshape(-1,)
print(B)

3
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [1]:
import cv2
import numpy as np
img = cv2.imread("Lenna.png")
print("original ", img.shape)
img1 = np.expand_dims(img, 0)
img2 = np.transpose(img1, (0, 3, 1, 2))
print("expand", img1.shape)
print("transpose",img2.shape)

original  (225, 225, 3)
expand (1, 225, 225, 3)
transpose (1, 3, 225, 225)
