In [1]:
a = [1,3,4]
print(a)
a[0] = 9
print(a)

b = [1, 3, 'string']
print(b)
b.append(6.24)
print(b)

print(2*a)
print(b*2)
c = [a[i] + a[i] for i in range(len(a))]
print(c)

[1, 3, 4]
[9, 3, 4]
[1, 3, 'string']
[1, 3, 'string', 6.24]
[9, 3, 4, 9, 3, 4]
[1, 3, 'string', 6.24, 1, 3, 'string', 6.24]
[18, 6, 8]


In [2]:
a = (1, 2, 3)
print(a)
b = (1, 3, 'string')
print(b)

a[0] = 2
a.append(4)

(1, 2, 3)
(1, 3, 'string')


TypeError: 'tuple' object does not support item assignment

In [3]:
info = {'A' : 2.3, 'B' : 'C', 5 : 'D'}
print(info)

info['A']= 5.2
print(info)

info['Hello'] = [1, 2, 3, 4, 'World.']
print(info)

{'A': 2.3, 'B': 'C', 5: 'D'}
{'A': 5.2, 'B': 'C', 5: 'D'}
{'A': 5.2, 'B': 'C', 5: 'D', 'Hello': [1, 2, 3, 4, 'World.']}


In [4]:
thisdict = {
    "brand" : "Ford",
    "model": "Mustang",
    "year" : 1964
}
print(thisdict["brand"])

Ford


In [5]:
thisdict = {
    "brand" : "Ford",
    "model": "Mustang",
    "year" : 1964
}
print(thisdict["brand"])
print(type(thisdict))

Ford
<class 'dict'>


In [6]:
thisdict = dict(name = "John", age = 36, country = "Norway")
print(thisdict)
print(type(thisdict))

{'name': 'John', 'age': 36, 'country': 'Norway'}
<class 'dict'>


In [7]:
items = [1, 2, 3, 4, 'Hello', 6.24]

for k in range(0, len(items)):
  print(items[k])
print('----------')
for item in items:
  print(item)
print('----------')
items = [[1,2], [3,4], [5,6]]
for item in items:
  print(item[0], item[1])
print('----------')
for item1, item2 in items:
  print(item1, item2)
print('----------')
info = {'A' : 1, 'B' : 2, 'C' : 3}
for key in info:
  print(key, info[key])
print('----------')
for key, value in info.items():
  print(key, value)

1
2
3
4
Hello
6.24
----------
1
2
3
4
Hello
6.24
----------
1 2
3 4
5 6
----------
1 2
3 4
5 6
----------
A 1
B 2
C 3
----------
A 1
B 2
C 3


In [8]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(a + a)

[1 2 3 4]
[2 4 6 8]


In [9]:
b = [1,2,3,4]
print(b + b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [10]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [11]:
a = np.array([[[1,2],[3,4]], [[1,2],[3,4]]])
print(a)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [12]:
a = np.array([1,2,3,4])
b = np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [13]:
import numpy as np
from numpy import linalg as LA
c = np.array([[ 1, 2, 3],
              [-1, 1, 4]])
print(LA.norm(c, axis=0))
print(LA.norm(c, axis=1))
print(LA.norm(c, ord=1, axis=1))
print(LA.norm(c, ord=2, axis=1))

[1.41421356 2.23606798 5.        ]
[3.74165739 4.24264069]
[6. 6.]
[3.74165739 4.24264069]


In [ ]:
a = np.array([[1],[2],[3],[4]])
print(a) #shape = (4,1)
print(a.T) #shape = (1,4)
print(a.T.reshape(-1,4))
print(a.shape)
print(a.T.reshape(-1,4).T.shape)

In [14]:
a = np.array([1,2,3,4])
b = a.reshape(4,-1)
print(a)
print(a.reshape(2,-1))
print(a.shape, ",", b.shape, ",", np.array([[1,2,3,4]]).shape)

[1 2 3 4]
[[1 2]
 [3 4]]
(4,) , (4, 1) , (1, 4)


In [15]:
a =np.array([1,2,3,4,5,6])
print(a.reshape(3,2))
print(a.shape)
b = a.reshape(3,-1)
print(b)
print(b.shape)
c = a.reshape(-1,2)
print(c)
print(c.shape)

[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [16]:
a =np.array([1,2,3,4,5,6])
print(a.reshape(3,2))
print(a.shape)
b = a.reshape(3,-1)
print(b)
print(b.shape)
c = a.reshape(-1,2)
print(c)
print(c.shape)

[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [17]:
A = np.array([[1, 4, 2, 0], [9, 5, 0, 0], [4, 0, 2, 4], [6, 1, 8,3]])
x = np.array([1, 2, 3, 4])
b = np.array([0, 0, 0, 0])
n = 4
for i in range(0, n):
  val = 0.0
  for j in range(0,n):
    #TODO 2
    val += A[i,j] * x[j]
  b[i] = val

print("calculate=", b)

b = np.dot(A,x)
print("dot=", b)

b = np.matmul(A,x)
print("matmul=", b)

b = A@x
print("A@x=", b)

b = A*x
print("A*x=", b)

calculate= [15 19 26 44]
dot= [15 19 26 44]
matmul= [15 19 26 44]
A@x= [15 19 26 44]
A*x= [[ 1  8  6  0]
 [ 9 10  0  0]
 [ 4  0  6 16]
 [ 6  2 24 12]]
