In [2]:
thisdict = {
    "brand": "ford",
    "model": "Mustang",
    "year": 1964
}
print(thisdict["brand"])
print(type(thisdict))

ford
<class 'dict'>


In [3]:
thisdict = dict(name = "John", age = 36, country = "Norway")

print(thisdict)
print(type(thisdict))

{'name': 'John', 'age': 36, 'country': 'Norway'}
<class 'dict'>


In [4]:
items = [1, 2, 3, 4, "Hello", 6.24]

for k in range(0, len(items)):
    print(items[k])
print("----------------")

for item in items:
    print(item)
print("----------------")

items = [[1,2], [3,4], [5,6]]
for item in items:
    print(item[0], item[1])
print("----------------")

for item1, item2 in items:
    print(item1, item2)
print("----------------")

info = {'A':1, 'B':2, 'C':3}
for key in info:
    print(key, info[key])
print("----------------")

for key, value in info.items():
    print(key, value)


1
2
3
4
Hello
6.24
----------------
1
2
3
4
Hello
6.24
----------------
1 2
3 4
5 6
----------------
1 2
3 4
5 6
----------------
A 1
B 2
C 3
----------------
A 1
B 2
C 3


In [5]:
items1 = [[1,2], [3,4], [5,6]]
items2 = [['A', 'B'], ['C', 'D'], ['E', 'F']]

print(items1)
print(items2)
print("----------------")

for digits, characters in zip(items1, items2):
    print(digits, characters)

[[1, 2], [3, 4], [5, 6]]
[['A', 'B'], ['C', 'D'], ['E', 'F']]
----------------
[1, 2] ['A', 'B']
[3, 4] ['C', 'D']
[5, 6] ['E', 'F']


In [6]:
a = []
for k in range(0, 5):
    a.append(k)

print(a)
print("----------------")

a = [k for k in range(0, 5)]
print(a)
print("----------------")

a = [k if (k + 1) % 2 else k * 5 + 1 for k in range(0, 5)]
print(a)
print("----------------")

a = [k for k in range(0, 5) if k % 2 == 0]
print(a)
print("----------------")

a = {k : k * 10 for k in range(0, 5)}
print(a)
print("----------------")

a = [1, 3, 4]
c = [a[i] + a[i] for i in range(len(a))]
print(c)

[0, 1, 2, 3, 4]
----------------
[0, 1, 2, 3, 4]
----------------
[0, 6, 2, 16, 4]
----------------
[0, 2, 4]
----------------
{0: 0, 1: 10, 2: 20, 3: 30, 4: 40}
----------------
[2, 6, 8]


In [8]:
import numpy as np

a = np.array([1,2,3,4])
print(a)
print(a + a)

[1 2 3 4]
[2 4 6 8]


In [9]:
b = [1,2,3,4]
print(b+b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [11]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [12]:
a = np.array([[[1,2],[3,4]], [[1,2], [3,4]]])
print(a)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [13]:
a = np.array([1,2,3,4])
b = np.array([[1], [2], [3], [4]])
print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [14]:
from numpy import linalg as LA

c = np.array([[1,2,3],
              [-1, 1, 4]])
print(LA.norm(c, axis=0))
print(LA.norm(c, axis=1))
print(LA.norm(c, ord=1, axis=1))
print(LA.norm(c, ord=2, axis=1))

[1.41421356 2.23606798 5.        ]
[3.74165739 4.24264069]
[6. 6.]
[3.74165739 4.24264069]


In [15]:
a = np.array([[1], [2], [3], [4]])

print(a)
print(a.T)
print(a.T.reshape(-1, 4))
print(a.shape)
print(a.T.reshape(-1, 4).T.shape)

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
[[1 2 3 4]]
(4, 1)
(4, 1)


In [16]:
a = np.array([1,2,3,4])
b = a.reshape(4, -1)
print(a)
print(a.reshape(2, -1))
print(a.shape,",",b.shape,",",np.array([[1,2,3,4]]).shape)

[1 2 3 4]
[[1 2]
 [3 4]]
(4,) , (4, 1) , (1, 4)


In [17]:
a = np.array([1,2,3,4,5,6])
print(a.reshape(3,2))
print(a.shape)

b = a.reshape(3, -1)
print(b)
print(b.shape)

c = a.reshape(-1, 2)
print(c)
print(c.shape)


[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [18]:
a = np.array([1,2,3,4])
print(a)
print(a.T)

b = a.reshape(4, -1)
print(b.shape)
print(b)
print(b.T.shape)

[1 2 3 4]
[1 2 3 4]
(4, 1)
[[1]
 [2]
 [3]
 [4]]
(1, 4)


In [20]:
A = np.array([[1,4,2,0], [9,5,0,0], [4,0,2,4], [6,1,8,3]])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0])
n = 4

for i in range(0, n):
    val = 0.0
    for j in range(0, n):
        val += A[i, j] + x[j]
    b[i] = val

print("calculate=", b)

b = np.dot(A, x)
print("dot=", b)

b = np.matmul(A, x)
print("matmul=", b)

b = A@x
print("A@x=", b)

b = A*x
print("A*x=", b)

calculate= [17 24 20 28]
dot= [15 19 26 44]
matmul= [15 19 26 44]
A@x= [15 19 26 44]
A*x= [[ 1  8  6  0]
 [ 9 10  0  0]
 [ 4  0  6 16]
 [ 6  2 24 12]]
