In [27]:
thisdict = {
    "brand" : "Ford",
    "model" : "Mustang",
    "year" : 1964
}
print(thisdict["brand"])
print(type(thisdict))

Ford
<class 'dict'>


In [29]:
thisdict = dict(name = 'John', age = 36, country = 'Norway')
print(thisdict)
print(type(thisdict))

{'name': 'John', 'age': 36, 'country': 'Norway'}
<class 'dict'>


In [ ]:
items = [1, 2, 3, 4, 'Hello', 6.24]

for k in range(0, len(items)):
    print(items[k])
print('-------------')

for item in items:
    print(item)
print('-------------')

items = [[1, 2], [3, 4], [5, 6]]
for item in items:
    print(item[0], item[1])
print('-------------')

for item1, item2 in items:
    print(item1, item2)
print('-------------')

info = {'A': 1, 'B': 2, 'C': 3}
for key in info:
    print(key, info[key])
print('-------------')

for key, value in info.items():
    print(key, value)


1
2
3
4
Hello
6.24
-------------
1
2
3
4
Hello
6.24
-------------
1 2
3 4
5 6
-------------
1 2
3 4
5 6
-------------
A 1
B 2
C 3
-------------
A 1
B 2
C 3


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(a+a)

[1 2 3 4]
[2 4 6 8]


In [ ]:
b=[1,2,3,4]
print(b+b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
a=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(a)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [ ]:
import numpy as np
from numpy import linalg as LA
c = np.array([[1,2,3],[-1,1,4]])
print(LA.norm(c,axis=0))
print(LA.norm(c,axis=1))
print(LA.norm(c, ord=1, axis=1))
print(LA.norm(c, ord=2, axis=1))

[1.41421356 2.23606798 5.        ]
[3.74165739 4.24264069]
[6. 6.]
[3.74165739 4.24264069]


In [ ]:
a = np.array([[1],[2],[3],[4]])
print(a)
print(a.T)
print(a.T.reshape(-1,4))
print(a.shape)
print(a.T.reshape(-1,4).T.shape)

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
[[1 2 3 4]]
(4, 1)
(4, 1)


In [ ]:
a=np.array([1,2,3,4])
b=a.reshape(4,-1)
print(a)
print(a.reshape(2,-1))
print(a.shape,',',b.shape,',',np.array([[1,2,3,4]]).shape)

[1 2 3 4]
[[1 2]
 [3 4]]
(4,) , (4, 1) , (1, 4)


In [ ]:
a = np.array([1,2,3,4,5,6])
print(a.reshape(3,2))
print(a.shape)
b=a.reshape(3,-1)
print(b)
print(b.shape)
c=a.reshape(-1,2)
print(c)
print(c.shape)

[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
a=np.array([1,2,3,4])
print(a)
print(a.T)
b=a.reshape(4,-1)
print(b.shape)
print(b)
print(b.T.shape)

[1 2 3 4]
[1 2 3 4]
(4, 1)
[[1]
 [2]
 [3]
 [4]]
(1, 4)


In [ ]:
c= np.array([1,2,3,4,5,6])

print(c[0])
print(c[5])
print(c[-1])
print(c[-2])
print(c[-6])
print(c[0:2])
print(c[2:5])
print(c[:2])
print(c[4:])
print(c[-2:])
print(c[:2],c[2:])
print(c[:4],c[4:])
print(np.arange(5,10))

1
6
6
5
1
[1 2]
[3 4 5]
[1 2]
[5 6]
[5 6]
[1 2] [3 4 5 6]
[1 2 3 4] [5 6]
[5 6 7 8 9]


In [ ]:
word = 'Python'

print(word[0])
print(word[5])
print(word[-1])
print(word[-2])
print(word[-6])
print(word[0:2])
print(word[2:5])
print(word[:2])
print(word[4:])
print(word[-2:])
print(word[:2]+word[2:])
print(word[:4]+word[4:])

P
n
n
o
P
Py
tho
Py
on
on
Python
Python


In [ ]:
A = np.array([[1,4,2,0],[9,5,0,0],[4,0,2,4],[6,1,8,3]])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0])
n = 4
for i in range(0,n):
  val = 0.0
  for j in range(0,n):
    val += A[i,i] * x[j]
  b[i] = val

print("caculate=",b)

b=np.dot(A,x)
print("dot=",b)

b=np.matmul(A,x)
print("matmul=",b)

b=A@x
print("A@x=",b)

b=A*x
print('A*x=',b)

caculate= [10 50 20 30]
dot= [15 19 26 44]
matmul= [15 19 26 44]
A@x= [15 19 26 44]
A*x= [[ 1  8  6  0]
 [ 9 10  0  0]
 [ 4  0  6 16]
 [ 6  2 24 12]]
