In [1]:
import numpy as np
from numpy import linalg as LA

a = np.array([1, 2, 3, 4])

print(a + a)
print(type(a + a))

b = [1, 2, 3, 4]
print(b + b)
print(type(b + b))

a = np.array([[1, 2], [3, 4]])
print(a + a)

a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a)
a = np.array([1, 2, 3, 4])
b = np.array([[1], [2], [3], [4]])
print(a)
print(a.shape)
print(b)
print(b.shape)

c = np.array([[1, 2, 3], [-1, 1, 4]])

print(LA.norm(c, axis=0))
print(LA.norm(c, axis=1))
print(LA.norm(c, ord=1, axis=1))
print(LA.norm(c, ord=2, axis=0))

a = np.array([[1], [2], [3], [4]])
print(a)
print(a.T)
print(a.T.reshape(-1, 4))
print(a.T.shape)
print(a.T.reshape(-1, 4).T.shape)

a = np.array([1, 2, 3, 4])
b = a.reshape(4, -1)
print(a)
print(a.reshape(2, -1))
print(a.shape, ",", b.shape, ",", np.array([[1, 2, 3, 4]]).shape)

a = np.array([1, 2, 3, 4, 5, 6])
print(a.reshape(3, 2))
print(a.shape)
b = a.reshape(3, -1)
print(b)
print(b.shape)
c = a.reshape(-1, 2)
print(c)
print(c.shape)

a = np.array([1, 2, 3, 4])
print(a)
print(a.T)
b = a.reshape(4, -1)
print(b.shape)
print(b)
print(b.T.shape)


A = np.array([[1, 4, 2, 0], [9, 5, 0, 0], [4, 0, 2, 4], [6, 1, 8, 3]])
x = np.array([1, 2, 3, 4])
b = np.array([0, 0, 0, 0])
n = 4
for i in range(n):
    val = 0.0
    for j in range(n):
        val += A[i][j] * x[j]
    b[i] = val

print("calculated b: ", b)

b = np.dot(A, x)
print("dot b: ", b)

b = np.matmul(A, x)
print("matmul b: ", b)

b = A @ x
print("A @ x: ", b)

b = A * x
print("A * x: ", b)

b = np.array([15, 19, 26, 44])

print("det = ", np.linalg.det(A))

x = np.linalg.solve(A, b)
print("solver = ", x)

x = np.dot(np.linalg.inv(A), b)
print("inv1 = ", x)

tmp_b = np.dot(A.T, b)
tmp_T = np.dot(A.T, A)
tmp_inv = np.linalg.inv(np.dot(A.T, A))
x = np.dot(tmp_inv, tmp_b)
print("inv2 = ", x)

[2 4 6 8]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 1, 2, 3, 4]
<class 'list'>
[[2 4]
 [6 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)
[1.41421356 2.23606798 5.        ]
[3.74165739 4.24264069]
[6. 6.]
[1.41421356 2.23606798 5.        ]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]
[[1 2 3 4]]
(1, 4)
(4, 1)
[1 2 3 4]
[[1 2]
 [3 4]]
(4,) , (4, 1) , (1, 4)
[[1 2]
 [3 4]
 [5 6]]
(6,)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[1 2 3 4]
[1 2 3 4]
(4, 1)
[[1]
 [2]
 [3]
 [4]]
(1, 4)
calculated b:  [15 19 26 44]
dot b:  [15 19 26 44]
matmul b:  [15 19 26 44]
A @ x:  [15 19 26 44]
A * x:  [[ 1  8  6  0]
 [ 9 10  0  0]
 [ 4  0  6 16]
 [ 6  2 24 12]]
det =  853.9999999999995
solver =  [1. 2. 3. 4.]
inv1 =  [1. 2. 3. 4.]
inv2 =  [1. 2. 3. 4.]
