In [10]:
my_tuple = ('A', 'B')
my_tuple = my_tuple + ('C',) #('C')만 하면 string

print(my_tuple, type(my_tuple))

('A', 'B', 'C') <class 'tuple'>


In [2]:
n = int(input("정수 n을 입력하세요: "))
num = 1

for i in range(n):
    for j in range(n):
        print(f"{num:2d}", end=' ')
        num += 1
    print()

정수 n을 입력하세요: 4
 1  2  3  4 
 5  6  7  8 
 9 10 11 12 
13 14 15 16 


In [12]:
import numpy as np
nn = int(input())
A = np.zeros((nn,nn))
for ii in range(nn):
  for jj in range(nn):
    A[ii,jj] = ii*nn + jj + 1
print(A)

4
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [14]:
reshape_A = A.reshape(-1,)
print(reshape_A)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]


In [7]:
from google.colab import drive
drive.mount('/content/drive/')
import sys
sys.path.append('/content/drive/MyDrive/Colab Notebooks/')

Mounted at /content/drive/


In [23]:
import numpy as np
import cv2

img = cv2.imread('/content/drive/MyDrive/Colab Notebooks/img.png')
print("shape:", img.shape)

img_expanded = np.expand_dims(img,0)
print("Batch :", img_expanded.shape)

# squeeze
img_squeezed = np.squeeze(img_expanded)
print("Squeeze:", img_squeezed.shape)

img_transposed = np.transpose(img_expanded, (0, 3, 1, 2))
print("Transpose:", img_transposed.shape)


shape: (275, 183, 3)
Batch : (1, 275, 183, 3)
Squeeze: (275, 183, 3)
Transpose: (1, 3, 275, 183)
