In [1]:
t = ("A", "B")

t = t + ("C",)

print(t)


('A', 'B', 'C')


In [11]:
import numpy as np
nn = int(input())
A = np.zeros((nn,nn))
for ii in range(nn):
    for jj in range(nn):
        A[ii][jj] = ii*nn+jj+1
print(A)

B = A.reshape(-1)
print(B)

4
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]


In [3]:
import cv2
import numpy as np
# img = cv2.imread("Lena.png")
img = np.random.randint(0, 256, (100, 200, 3), dtype=np.uint8)

print("oritignal ", img.shape)
img1 = np.expand_dims(img, 0)
print("expand ", img1.shape)
img2 = np.transpose(img1, (0, 3, 1, 2))
print("transpose ", img2.shape)

oritignal  (100, 200, 3)
expand  (1, 100, 200, 3)
transpose  (1, 3, 100, 200)
