In [4]:
import numpy as np
import cv2

tpl = ('A', 'B')
print(tpl)
lst = list(tpl)
lst.append('C')
tpl = tuple(lst)
print(tpl)

N = int(input())
array = np.zeros((N, N))
for i in range(N):
    for j in range(N):
        array[i][j] = i * N + j + 1
print(array)

array = array.reshape(1, N ** 2)
print(array)

('A', 'B')
('A', 'B', 'C')
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20. 21. 22. 23. 24. 25.]]


In [ ]:
import numpy as np
import cv2

img = cv2.imread('1.webp')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = np.expand_dims(img, axis=0)
img = np.transpose(img, (0, 3, 1, 2))
print(img.shape)


def filter2D(image, ddepth, kernel):
    output = np.zeros_like(image)
    k_height, k_width = kernel.shape
    height, width = image.shape
    pad_height = k_height // 2
    pad_width = k_width // 2
    padded_image = np.pad(image, ((pad_height, pad_height),
                          (pad_width, pad_width)), mode='constant', constant_values=0)
    for i in range(height):
        for j in range(width):
            region = padded_image[i:i + k_height, j:j + k_width]
            output[i, j] = np.sum(region * kernel)
    return output


img = cv2.imread('1.webp', cv2.IMREAD_GRAYSCALE)
kernel = np.array([[1, 1, 1], [1, -8, 1], [1, 1, 1]])
output = filter2D(img, -1, kernel)
cv2.imshow('output', output)
cv2.waitKey(0)


(1, 3, 600, 600)
